CXX = g++

CXXFLAGS = -Wall -std=c++17

TARGET = hello.exe
SOURCES = hello.cpp

all: $(TARGET)

$(TARGET): $(SOURCES)
    $(CXX) $(CXXFLAGS) : $(TARGET) $(SOURCES)
clean:
    del : $(TARGET)